// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace My_Project
{
    public partial class LibraryContext : DbContext
    {
        public LibraryContext()
        {
        }

        public LibraryContext(DbContextOptions<LibraryContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BkNotifications> BkNotifications { get; set; }
        public virtual DbSet<TblBooks> TblBooks { get; set; }
        public virtual DbSet<TblGivingBack> TblGivingBack { get; set; }
        public virtual DbSet<TblSelectedBook> TblSelectedBook { get; set; }
        public virtual DbSet<TblUsers> TblUsers { get; set; }
        public virtual DbSet<TeacherApproving> TeacherApproving { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=KORAY;Initial Catalog=Library;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Turkish_CI_AS");

            modelBuilder.Entity<TblGivingBack>(entity =>
            {
                entity.Property(e => e.BookToGiveBack).IsFixedLength(true);

                entity.Property(e => e.WhichMail).IsFixedLength(true);
            });

            modelBuilder.Entity<TblSelectedBook>(entity =>
            {
                entity.HasKey(e => e.SelectedBookId)
                    .HasName("PK_TakenBooks");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}