// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace My_Project
{
    [Table("tblBooks")]
    public partial class TblBooks
    {
        [Key]
        [Column("BookID")]
        public int BookId { get; set; }
        [Required]
        [StringLength(160)]
        public string Name { get; set; }
        [Required]
        [StringLength(160)]
        public string Genre { get; set; }
        public int ReleaseDate { get; set; }
        public int Pages { get; set; }
        [Required]
        [StringLength(160)]
        public string Author { get; set; }
        public int Number { get; set; }
    }
}