// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace My_Project
{
    [Table("tblGivingBack")]
    public partial class TblGivingBack
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(160)]
        public string WhichMail { get; set; }
        [Required]
        [StringLength(160)]
        public string BookToGiveBack { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime WhenLeased { get; set; }
    }
}