// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace My_Project
{
    [Table("tblSelectedBook")]
    public partial class TblSelectedBook
    {
        [Key]
        public int SelectedBookId { get; set; }
        [Required]
        [StringLength(128)]
        public string Email { get; set; }
        public int UserType { get; set; }
        [Required]
        [StringLength(128)]
        public string WhichBook { get; set; }
        [Required]
        [StringLength(128)]
        public string Author { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime LeasedDate { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime RestitutionDate { get; set; }
    }
}